### ISSUE TITLE
object destructuring assignment not working 

### ISSUE THREAD

**Issue by moderadev** [sebastienros/esprima-dotnet#100]
const { a, b, ...c } = { a: 1, b: 2, c: 3 };

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

http://esprima.org/demo/parse.html?code=const%20%7B%20a%2C%20b%2C%20...c%20%7D%20%3D%20%7B%20a%3A%201%2C%20b%3A%202%2C%20c%3A%203%20%7D%3B

**Comment by lahma** [comment]
Tested and given example works with the current head which recently got missing features back-ported.
