### ISSUE TITLE
ArgumentOutOfRangeException for scripts with multiline strings

### ISSUE THREAD

**Issue by lekrus** [sebastienros/esprima-dotnet#131]
With the latest 2.0.0-beta1303

The following valid JS code:
```JavaScript
var str = 'test \
d'+'test \
test'+'f';
```
will throw ArgumentOutOfRangeException while parsing with Loc=true option

```c#
var code = "var str = 'test \\\nd'+'test \\\ntest'+'f';";

var parser = new JavaScriptParser(code, new ParserOptions {Loc = true});
parser.Invoking(_ => parser.ParseScript())
	.Should().NotThrow(); // TODO: this fails

parser = new JavaScriptParser(code);
parser.Invoking(_ => parser.ParseScript())
	.Should().NotThrow();

```

**Comment by lahma** [comment]
Created a PR for https://github.com/sebastienros/esprima-dotnet/pull/132 , but we need to wait for original esprima's take on the matter: https://github.com/jquery/esprima/issues/2032

**Comment by lekrus** [comment]
thanks a lot for the quick fix!

**Comment by lahma** [comment]
A new version is now also on NuGet containing this fix.
