### ISSUE TITLE
ParserException: InvalidRegularExpression on valid regex

### ISSUE THREAD

**Issue by MaceWindu** [sebastienros/esprima-dotnet#146]
Regular expression literal:
```js
/(?:\s|\/\/.*|\/\*[^]*?\*\/)*/g
```

Source `@babel\parser\lib\index.js`
```js
const skipWhiteSpace = /(?:\s|\/\/.*|\/\*[^]*?\*\/)*/g;  
```

[index.zip](https://github.com/sebastienros/esprima-dotnet/files/5966005/index.zip)

**Comment by MaceWindu** [comment]
Another case:
```js
var match = text.match(/^(\s*)([^]*\S)(\s*)$/); 
```

`postcss-safe-parser\lib\safe-parser.js`
[safe-parser.zip](https://github.com/sebastienros/esprima-dotnet/files/5966243/safe-parser.zip)

**Comment by MaceWindu** [comment]
```js
var regex = /{[^]*/gm,
```

`specificity\specificity.js`
[specificity.zip](https://github.com/sebastienros/esprima-dotnet/files/5966253/specificity.zip)

**Comment by MaceWindu** [comment]
```js
const pathToArgumentName = input => {
		return input
			.replace(/\./g, "-")
			.replace(/\[\]/g, "")
			.replace(
				/(\p{Uppercase_Letter}+|\p{Lowercase_Letter}|\d)(\p{Uppercase_Letter}+)/gu,
				"$1-$2"
			)
			.replace(/-?[^\p{Uppercase_Letter}\p{Lowercase_Letter}\d]+/gu, "-")
			.toLowerCase();
	}; 
```

`webpack\lib\cli.js`
[cli.zip](https://github.com/sebastienros/esprima-dotnet/files/5966430/cli.zip)

**Comment by jimbo118** [comment]
I also ran into this:

> var parser = new Esprima.JavaScriptParser(@"var O = /[^]*? (:[rp] [el] a[\w -]+)[^]*/");
> var program = parser.ParseScript();

Throw: 

> ParserException: Line 1: Invalid regular expression
> Esprima.Scanner.ThrowUnexpectedToken (System.String message) (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.Scanner.TestRegExp (System.String pattern, System.String flags) (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.Scanner.ScanRegExp () (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.NextRegexToken () (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.ParsePrimaryExpression () (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.InheritCoverGrammar[T] (System.Func`1[TResult] parseFunction) (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.ParseLeftHandSideExpressionAllowCall () (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.InheritCoverGrammar[T] (System.Func`1[TResult] parseFunction) (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.ParseUpdateExpression () (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.ParseUnaryExpression () (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.InheritCoverGrammar[T] (System.Func`1[TResult] parseFunction) (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.ParseExponentiationExpression () (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.InheritCoverGrammar[T] (System.Func`1[TResult] parseFunction) (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.ParseBinaryExpression () (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.InheritCoverGrammar[T] (System.Func`1[TResult] parseFunction) (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.ParseConditionalExpression () (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.ParseAssignmentExpression () (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.IsolateCoverGrammar[T] (System.Func`1[TResult] parseFunction) (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.ParseVariableDeclaration (System.Boolean& inFor) (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.ParseVariableDeclarationList (System.Boolean& inFor) (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.ParseVariableStatement () (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.ParseStatement () (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.ParseStatementListItem () (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)
> Esprima.JavaScriptParser.ParseScript (System.Boolean strict) (at <8417cb4e01e54c02aaa0c58a3fa07237>:0)

But it's valid on the Esprima online parserpage: 

> [Esprima Online Parser](https://esprima.org/demo/parse.html?code=%2F%2F%20Life%2C%20Universe%2C%20and%20Everything%0Avar%20O%20%3D%20%2F%5B%5E%5D*%3F%20(%3A%5Brp%5D%20%5Bel%5D%20a%5B%5Cw%20-%5D%2B)%5B%5E%5D*%2F%0A)

**Comment by sebastienros** [comment]
I was able to isolate the issue for all these reports to `/[^]/`. Working on the fix.
