### ISSUE TITLE
Optional chaining operator not supported

### ISSUE THREAD

**Issue by MaceWindu** [sebastienros/esprima-dotnet#150]
```
ParserException: 'Line 23: Unexpected token .'
```

```js
if (binding?.constantViolations.length) { 
```

`@babel\preset-modules\src\plugins\transform-edge-function-name\index.js`

[index.zip](https://github.com/sebastienros/esprima-dotnet/files/5966361/index.zip)

**Comment by sebastienros** [comment]
Note that esprima doesn't support this one either https://esprima.org/demo/parse.html?code=binding%3F.constantViolations.length

**Comment by MaceWindu** [comment]
https://github.com/jquery/esprima/pull/2048

**Comment by jogibear9988** [comment]
@sebastienros 
If the pull req will be merged in esprima will you also support it ? (is your code automaticly generated from esprima code?).
or does this need to be manualy implemented? (so someone should work on a pull request)

**Comment by lahma** [comment]
When Esprima PR is merged, the change needs to be ported to .NET version manually.

**Comment by jogibear9988** [comment]
@lahma @sebastienros esprima has now merged this (and many other commits).

question:
Is there a list you keep track wich commits from esprima are already migrated?

**Comment by sebastienros** [comment]
We don't have a list, just follow the branch. Do you think you could send a PR to port this fix?

**Comment by jogibear9988** [comment]
I can look if I will find time.
I think this one is also missing: https://github.com/jquery/esprima/commit/ab6420b85cced6b55730a5204594683a17941108

**Comment by lahma** [comment]
@jogibear9988 yes, the two latest feature commits haven't been ported. Please reference relevant commits in your commits/PR so we have some kind of book keeping at least 🙂

**Comment by lahma** [comment]
@jogibear9988 I think I can handle at least the first one, give us a holler when you're about to start if you find the time so we don't overlap.

**Comment by jogibear9988** [comment]
@lahma wich one is the first one?

**Comment by lahma** [comment]
Ah sorry, chronologically oldest, so in my mind first in queue, so the template literal fix, not related to this issue. Just making sure there are no gaps.

**Comment by jogibear9988** [comment]
I will not work on this the next days, need to work on my html designer framework. If I'll get back to this (and my other pull req here ), and noone has done the fix before, I'll take a look.

**Comment by lahma** [comment]
The template literal revision is done https://github.com/sebastienros/esprima-dotnet/pull/155

**Comment by lahma** [comment]
@jogibear9988 I read the PR for optional chaining now more carefully and it can be a bit tedious as it needs to be integration tested via Jint as the 262 test suite is there. I'll try to have a look this evening.
