### ISSUE TITLE
SourceType enum pollutes global namespace

### ISSUE THREAD

**Issue by dahauns** [sebastienros/esprima-dotnet#151]
Is there a reason that 
https://github.com/sebastienros/esprima-dotnet/blob/3d910f317ed9ad7ad52aef9809ff73d2fc3257bc/src/Esprima/SourceType.cs
has no namespace?

As it is, it shadows any namespaced entity named SourceType you might have in your project - *as soon as you add the package to your project* (no "using" required).

**Comment by sebastienros** [comment]
Probably a mistake. We should look for others missing.

**Comment by dahauns** [comment]
Ah, good to know.
Looking at the assembly in Object Browser/R# Assembly Explorer, SourceType seems to be the only affected entity.
