### ISSUE TITLE
Write AST back to Script

### ISSUE THREAD

**Issue by jogibear9988** [sebastienros/esprima-dotnet#152]
Is there a Method to write the AST back to a script?

I want to use the library to minimize scripts direct in my c# webserver. So I want to parse to AST, optmize the AST and write it back to a script.

**Comment by oujunke** [comment]
I have developed a project for this, if you are interested, you can refer to it, there may be shortcomings at present [project address](https://github.com/oujunke/EsprimaToJs2)

**Comment by jogibear9988** [comment]
I've also started using a Visitor: https://github.com/sebastienros/esprima-dotnet/pull/154
But it's not yet finished.

Is yours finished?

**Comment by jogibear9988** [comment]
My Plan is with mine, to use it for on the fly minification in our C# Webserver. But at first I need to fix some of the not supported ES6 features we use. (At first in Esprima, before they are converted to esprima.net)

**Comment by oujunke** [comment]
I am a newly developed project, not all completed

**Comment by oujunke** [comment]
It's just that the js that I need to convert is compatible, and the others are not guaranteed

**Comment by jogibear9988** [comment]
fix for this #154

**Comment by adams85** [comment]
Resolved by #291. Can be closed now.
