### ISSUE TITLE
Assignment operators are parsed incorrectly in binary expressions

### ISSUE THREAD

**Issue by ftpguy** [sebastienros/esprima-dotnet#174]
Take this code for example:

	var n;
	var x = 1 == n = 2;

In the binary expression, `1` should be on the left and the assignment of `n = 2` should be on the right like `var x = (1 == (n = 2))`. Instead, `1`  is on the right and `n` is on the left like `var x = (1 == n) = 2`, so the parser thinks the code is trying to assign `2` to the binary operator.

I am creating a JS to c# converter and this is causing an issue in me being able to identify `n = 2` as an assignment expression which it is.

**Comment by lahma** [comment]
I think your example is not valid if you run with `Tolerant = false` option:

```
Esprima.ParserException: Line 2: Invalid left-hand side in assignment
```

Node doesn't like the sample either:

```
Welcome to Node.js v14.17.0.
Type ".help" for more information.
> var n;
undefined
> var x = 1 == n = 2;
var x = 1 == n = 2;
        ^^^^^^

Uncaught SyntaxError: Invalid left-hand side in assignment
```

[Adding parentheses seems to make the parser happy](https://esprima.org/demo/parse.html?code=var%20n%3B%0Avar%20x%20%3D%201%20%3D%3D%20(n%20%3D%202)%3B).

**Comment by ftpguy** [comment]
Ah, you are _right_. I actually tried putting parens around the assignment and I somehow read the debugger values wrong. When I write it like `1 == (n = 2)`, it indeed recognizes it properly. Also, you're right about the syntax being invalid as I also tried my original example in codepen and it didn't like it.

Anyway, thanks for clearing that up and sorry for making something out of nothing.

**Comment by ftpguy** [comment]
Also, thanks for this great library. It works very well with the visitor pattern. Overall, it's been great to work with.

**Comment by lahma** [comment]
Thanks for the kind words and glad that you got it sorted!
