### ISSUE TITLE
TemplateLiteral orders its child nodes with TemplateElements first and tokens last

### ISSUE THREAD

**Issue by ftpguy** [sebastienros/esprima-dotnet#177]
Take this JS for example:

    var name = "Bob";
    var age = 30;
    var s = `Name: ${name}, Age: ${age}`;

The child nodes are ordered like this:

![image](https://user-images.githubusercontent.com/39510308/126872180-5ff3b8a6-265d-49ff-ac1a-2d30891f0ee7.png)

I had to write this code as a workaround which basically iterates through the TemplateElements and then looks ahead in the collection for its corresponding token. It works, but it seems like the nodes should be ordered as they appear in the string so that you can just do a simple `for each` through them.

        public static IEnumerable<Node> EnumerateChildNodes(this TemplateLiteral node)
        {
            var max = (int)Math.Ceiling((double)node.ChildNodes.Count / 2);

            for (int i = 0; i < max - 1; i++)
            {
                yield return node.ChildNodes[i];

                yield return node.ChildNodes[i + max];
            }

            yield return node.ChildNodes[max - 1];
        }

**Comment by lahma** [comment]
So maybe you want to submit a PR to fix the ordering?

**Comment by ftpguy** [comment]
If you mean submitting a PR where I basically implement my work-around solution above, I am thinking a more elegant solution would be best for optimal performance. The actual fix would probably need to be made closer to where the parsing and node building is occurring. I am pretty sure I could figure that out, but I am preoccupied with other projects and think that would be better suited for someone already familiar with the code base.

For now, my work-around is suitable for what I am doing which is converting JS to c# since I only need to do a conversion once. Seems like this would be an issue contributors to the code would want to know about, though.
