### ISSUE TITLE
AST improvement suggestions

### ISSUE THREAD

**Issue by adams85** [sebastienros/esprima-dotnet#180]
I'd welcome the following improvements to the AST:

* Introduction of an `IClass` interface for `ClassDeclaration` and `ClassExpression` for the same purpose which `IFunction` serves considering `FunctionDeclaration` and `FunctionExpression`: for allowing polymorphic handling of these types.

* Moving the `Local` property of `ImportDefaultSpecifier`, `ImportNamespaceSpecifier` and `ImportSpecifier` to their base class `ImportDeclarationSpecifier` to avoid [this](https://github.com/adams85/bundling/blob/d9a649cbeeabcff3810c439971e732ffdddd9bcc/source/Bundling.EcmaScript/Internal/Helpers/VariableScopeBuilder.cs#L181). If this is not acceptable (e.g. because we expect that other types of declaration specifiers may be introduced in the future), introducing an interface can also be a viable alternative.

Are you open for a PR addressing these suggestions?

**Comment by lahma** [comment]
FYI, AST related work got published to NuGet yesterday.

**Comment by adams85** [comment]
Great news! Thank you, Marko!

**Comment by lahma** [comment]
Thank *you* for all the help and iterating towards perfection 🙂
