### ISSUE TITLE
Parser error on Asynchronous iteration and Asynchronous generators

### ISSUE THREAD

**Issue by adams85** [sebastienros/esprima-dotnet#183]
The parser has issues with the aforementioned [ES2018 features](https://exploringjs.com/impatient-js/ch_new-javascript-features.html#new-in-es2018):

* ~~*Asynchronous iteration* works only when `ParserOptions.Tolerant` is set to false, otherwise it results in `ParserException`. Sample input:~~
   ```js
   for await (const x of syncToAsyncIterable(['a', 'b'])) {
     console.log(x);
   }
   ```
  results in error as expected but is parsed fine in async contexts:
  ```js
   async function f() {
     for await (const x of syncToAsyncIterable(['a', 'b'])) {
       console.log(x);
     }
   }
  ```

* *Asynchronous generators* results in in `ParserException` regardless the `ParserOptions.Tolerant` setting. Sample input: 
   ```js
   async function* asyncGen() {
     yield someValue;
   }
   ```

Library version: 2.0.2

**Comment by lahma** [comment]
I think this is a problem also in the original Esprima JS project so maybe need to file an issue there.

**Comment by adams85** [comment]
@lahma You mean it has to be fixed in the original Esprima first? That'd be a bummer because this is kinda blocking for my lib...

BTW, have you seen [this comment](https://github.com/sebastienros/esprima-dotnet/issues/179#issuecomment-898889925)? Could you re-open that issue? (Unfortunately I can't.)

**Comment by lahma** [comment]
> @lahma You mean it has to be fixed in the original Esprima first? That'd be a bummer because this is kinda blocking for my lib...

Can be fixed on either side first, just a good practice to get the fix ported also to the other side to keep code consistent between the implementations.

> BTW, have you seen [this comment](https://github.com/sebastienros/esprima-dotnet/issues/179#issuecomment-898889925)? Could you re-open that issue? (Unfortunately I can't.)

Would you like to submit a PR to fix remaining issue(s)?

(sorry I fat-fingered and edited your comment first)

**Comment by adams85** [comment]
@lahma I can take the other issue (the minor strict mode bug) but I'm not familiar enough with the parser to tackle this one.

**Comment by lahma** [comment]
Seems that there's already [a work item](https://github.com/jquery/esprima/issues/1990) on Esprima side.

**Comment by lahma** [comment]
By a cursory look it's enough two change:

`var isGenerator = isAsync ? false : Match("*");`

to 

`var isGenerator = Match("*");`

in two places. Breaks two (now invalid) test cases and lacks test cases and JSON trees for results.

**Comment by adams85** [comment]
@lahma Now this is the only blocking issue left for me. Are you working on this? If not, I might give it a shot.

**Comment by lahma** [comment]
I have some work done, it should be pretty close to be PR ready against the JS version. Got to get my thoughts back together and check where I left the work..

**Comment by adams85** [comment]
Great news!

BTW, in the meantime I realized that I was mistaken about the *Asynchronous iterations* bug. It's parsed alright in async contexts, just the error message is not too helpful. I'll update the issue description.

However, I noticed that the parser skates over invalid usages of `await` in the case of `for` and `for...in` loops even when tolerant parsing is switched off:

```js
(async () => { 
  for await (;;) { }
})()
```
is accepted without an error.

I've been making some progress on this though, I'll submit it as a PR soon.

**Comment by lahma** [comment]
Here's the draft PR on C# side, I'm working on both JS and C# to see how the implementation works: https://github.com/sebastienros/esprima-dotnet/pull/190

**Comment by sebastienros** [comment]
It's not even implemented on esprima's side?

**Comment by lahma** [comment]
Hey welcome back @sebastienros ! Not yet implemented, I'm working on both sides to see what is missing: https://github.com/jquery/esprima/pull/2101

**Comment by sebastienros** [comment]
That's awesome!

**Comment by lahma** [comment]
I've completed [the changes on JS side](https://github.com/jquery/esprima/pull/2101) and also have the relevant code on .NET side ready (actually developed on .NET sided as debugging is waaaay easier). Waiting for acceptance there.

**Comment by adams85** [comment]
@lahma May I expect a 2.x release after these changes get accepted and merged? I'd like to know that to be able to decide whether or not to stall releasing one of my libs depending on Esprima.NET.

**Comment by lahma** [comment]
I'd be happy to have a 2.x release with these fixes that have landed and including this too (unless @sebastienros objects). If we don't hear back from JS side for a while we can also consider merging beforehand and fixing later if needed.

**Comment by adams85** [comment]
Excellent, thank you!

**Comment by lahma** [comment]
I've merged in the changes as the JS PR seems to be in standstill. Your three examples provided in summary now parse without errors. Let's iterate more later if needed...

**Comment by lahma** [comment]
And the JS PR was also just merged.
