### ISSUE TITLE
Some scripts fail

### ISSUE THREAD

**Issue by sebastienros** [sebastienros/esprima-dotnet#19]
Knockout and Loadash

https://github.com/rushfrisby/jsnetperf/pull/2

**Comment by lahma** [comment]
Both are actually Jint issues:

* Knockout - torelant is false, causes proto check to fail
* Lodash, there's a bug in implicit equality operators + code is insanely slow, trying to address both

**Comment by lahma** [comment]
@sebastienros this can be closed, latest NuGet release works against the benchmark suite when tolerant = true (for knockoutjs).
