### ISSUE TITLE
Tolerate and fix script errors

### ISSUE THREAD

**Issue by h15ter** [sebastienros/esprima-dotnet#194]
First of all, I'd like to thank @sebastienros and all the contributors for this amazing project. You do the great job!

Here is what I want to achieve:
1. Parse the script to the end, tolerating all kinds of errors
2. Locate each error and fix it automatically
3. Write fixed version back to script

Here are the problems I face:
1. Some errors can be tolerated, while others throw immediately. For example, even with options/error handler set to tolerate errors, parsing the following script throws early on colon char. Can it be solved somehow?
```
function test() {
    var id: int = 123;
    return id + 1;
}
```
2. In the example above, stripping type specification (`: int`) makes the code valid javascript. I want to do that automatically, but I need to somehow find the error boundary. Do you have an idea on how this might be done?
3. Now let's assume 1 and 2 are solved somehow, so I have a fixed AST generated. What are the best options I have for writing it back to the javascript?

Thanks!

**Comment by lahma** [comment]
For TS part it might work to compile it to ES2022 syntax so it should pretty much be the version with typings stripped out, but I think there's no silver bullet.

**Comment by lahma** [comment]
Closing as it's limited what parsing can do besides the current tolerant mode.
