### ISSUE TITLE
Support for exporting another module's contents as namespace

### ISSUE THREAD

**Issue by pluethi1** [sebastienros/esprima-dotnet#195]
Hi, first of all, I love this project and Jint. 

I am currently working on module support for Jint in my own fork of the repo and I noticed the parsing of export statements is not complete. 

In the spec (https://tc39.es/ecma262/#prod-ExportFromClause) for the _ExportFromClause_ you should be able to export from another module and assign the contents to a namespace. For example:
```javascript
export * as ns from "mod"; 
```

If there are no objections, i'd start work on a PR adressing this issue.

**Comment by lahma** [comment]
Great to hear that you are willing to lend a hand! As this project tries to keep quite 1:1 resemblance with the JS version, it's always good to check JS project first. I see there's an issue over there already and a PR so I'd suggest to study the PR and base work on that. It will likely be the code that will be merged into JS version.

https://github.com/jquery/esprima/issues/2053

**Comment by lahma** [comment]
@pluethi1 thanks for handling this. Was the module loader support something you are planning to contribute to Jint? Just making sure that there won't be any work overlap.

**Comment by lahma** [comment]
Great to hear! 👍🏻 I think nobody is working on it (yet!). Please comment the issue so people are aware, I think it's then even possible to assign the issue to you.  

When working, please create a separate branch to your repo, it will make things easier compared to using main directly.
