### ISSUE TITLE
Change AstVisitor (& ToJavascriptVisitor) to be able to change the Expression

### ISSUE THREAD

**Issue by jogibear9988** [sebastienros/esprima-dotnet#210]
@sebastienros @lahma 
Would it be okay if I change the Visitors to look like this?
https://github.com/microsoft/referencesource/blob/master/System.Core/System/Linq/Expressions/ExpressionVisitor.cs

But one more question:
Why is the a Accept Method on every AstNode for the Visitor?

**Comment by lahma** [comment]
I'm pinging @adams85 for the discussion as he's been active on this front and implementing visitor pattern to his needs.

**Comment by sebastienros** [comment]
I really want to understand how this pattern works to modify a tree. I think I understand why Visitors are useful to navigate through nodes to find specific ones. But for altering them, I am not sure about the thought process. For instance let's say I want to remove specific nodes, or if I want to change a property of a set of nodes (like change the name of a variable).

Would it also make sense to provide extension methods and pre-defined visitors for such tasks?

**Comment by jogibear9988** [comment]
Altering is easy, every VisitXXXX Method calls Visit for each of it's sub Expressions. If any of the Visits returns a new Expression, the VisitXXX itself also returns a new expression with its parameters...

To Remove a Node, a VisitXXX could Return not the original, but one of it's child expressions. And a Visit does not need to return the same type as was beeing visited.

**Comment by jogibear9988** [comment]
here is a nice sample...
https://khalidabuhakmeh.com/linq-expression-visitors#changing-the-expression-tree

**Comment by adams85** [comment]
> Why is the a Accept Method on every AstNode for the Visitor?

That is for double dispatch, it's part of the standard implementation of the [Visitor pattern](https://en.wikipedia.org/wiki/Visitor_pattern). [The current implementation of .NET expression trees](https://github.com/dotnet/runtime/blob/v6.0.0/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/Expression.cs#L161) has this as well.

See [this discussion](https://github.com/sebastienros/esprima-dotnet/pull/185) for details.

> Would it be okay if I change the Visitors to look like this?

What would you like to change exactly? Do you want the `Visit` method to return the visited subtree?

I haven't done it because it would be a breaking change. However, in a new major version it's ok to me.

**Comment by sebastienros** [comment]
Fine by me, @lahma ?. I see the need of being able to modify an AST, and it being immutable we need a visitor that can do it. I think it was the original intent of immutability + visitor (@atifaziz ?).

**Comment by lahma** [comment]
I agree with the above points and allowing to return new node presentation after optimize of whatever is happening. Jint doesn't directly need such capabilities but could benefit from in-between optimizer that would transform the AST.

Current released Esprima is quite usable feature-wise so breaking changes are probably welcome and we can do a major version bump when needed (actual release nears). There's also the public API overhaul thing, but can be done incrementally...

No sure if we should support deleting nodes, maybe just return `EmptyStatement`, interpreter can discard them? But generally I guess returning whatever wanted in this case will replace the original so original is effectively deleted.

**Comment by jogibear9988** [comment]
So should I do this, or will someone other work on this?

**Comment by lahma** [comment]
I can probably vouch for me and @sebastienros *not* doing it, if @adams85 isn't keen to jump into it, I'd say you have free hands. But if possible, it would be great if @adams85 would also have time to review as he's been recent main consumer for this visitor feature.

**Comment by adams85** [comment]
I'll gladly do the review.

**Comment by jogibear9988** [comment]
@adams85 

maybe you can also take a look at the pull req, I've a few questions...

https://github.com/sebastienros/esprima-dotnet/pull/211

**Comment by adams85** [comment]
Resolved by #243 and #253. Can be closed now.
