### ISSUE TITLE
Typescript compiler v4.5 and Jint v3 won't work

### ISSUE THREAD

**Issue by viceice** [sebastienros/esprima-dotnet#212]
Hi, it seems the latest typescript compilter v4.5.2 won't work on Jint.

https://github.com/viceice/dotnet-ts-testing/pull/177

The CI job simply never finished. Works with typescipt v4.4.4

**Comment by lahma** [comment]
I've transferred the issue here, as it's Esprima going into infinite loop, minimal test case:

```csharp
[Fact]
public void ShouldHandleMultiLineMatch()
{
    var scanner = new Scanner("", new ParserOptions { AdaptRegexp = true });
    var regex = scanner.TestRegExp("\\$", "gm");
    Assert.NotNull(regex);
}
```

**Comment by lahma** [comment]
@viceice thanks for reporting this and working with the engines! You should now see a new release `3.0.0-beta-2037` on NuGet that should fix the problem.

**Comment by viceice** [comment]
Thank you for the fast fix. Renovate should suggest that update soon. 🤗
