### ISSUE TITLE
PrivateIdentifier support

### ISSUE THREAD

**Issue by javidsho** [sebastienros/esprima-dotnet#215]
Is there any chance to have support for private identifiers?

https://tc39.es/ecma262/#prod-PrivateIdentifier

**Comment by jogibear9988** [comment]
look: https://github.com/sebastienros/esprima-dotnet/pull/205 it is already there

**Comment by javidsho** [comment]
Thanks. I'm closing this one, then.

**Comment by jogibear9988** [comment]
small thing maybe is missing "#aa in obj".
but that was added to spec later.
Maybe it also already works.
But I work on this for esprima-next and then I'll create a pull here if it does not already

**Comment by javidsho** [comment]
Thanks. That's precisely what was missing. I tried parsing with # and a parse exception occurred.

**Comment by jogibear9988** [comment]
a '#' should work, but maybe not in an 'in' condition.
But i dont know if the code is already in a nuget

**Comment by jogibear9988** [comment]
confused??

code like this should work:

     class aa {
          #bb;
          cc() {
                this.#bb = 3;
           }
      }

this not yet:

     class aa {
          #bb;
          cc(dd) {
                var a = #bb in dd;
           }
      }

**Comment by javidsho** [comment]
Oh I see now. It's obvious that in the scenario I was testing it should've worked out. I'll try again and let you know.

**Comment by jogibear9988** [comment]
@javidsho 
could be that it currently does not work.
There was a case in scanner missing...
I fixed this here: https://github.com/sebastienros/esprima-dotnet/pull/221
