### ISSUE TITLE
Use System.Span

### ISSUE THREAD

**Issue by lahma** [sebastienros/esprima-dotnet#22]
Opening for tracking. My masterpiece where Slice tries to match common keywords will come much simpler. This will affect a lot of public API by having ReadOnlySpan<char> instead of string, but all should become quite alloc-free.

**Comment by lahma** [comment]
I'm leaning towards having custom [TextSpan](https://github.com/sebastienros/parlot/blob/main/src/Parlot/TextSpan.cs) like Parlot has and then allowing span-based operations via it's `Span` property.

**Comment by lahma** [comment]
@Xicy I might have some prototype in some branch, I probably need to check if it's any good starting point and how far away from current main...

**Comment by lahma** [comment]
I've tested this with StringSegment and memory benefits are very little as long as Token instances dominate allocations.

**Comment by adams85** [comment]
In the light of work done recently we can consider this done, right?

**Comment by lahma** [comment]
Indeed!
