### ISSUE TITLE
the End Position more than 1 character on comment

### ISSUE THREAD

**Issue by xp44mm** [sebastienros/esprima-dotnet#227]
```js
// single-line comment
```

use code:
```f#
scanner.Source.[comment.Start..comment.End]
```

the result is:
```js
// single-line comment\r
```

the block comment is also this case.

the comment.Type always is `Block` both comment.MultiLine is true and false.

**Comment by adams85** [comment]
Couldn't reproduce this using the latest version. Maybe got fixed along the way.
