### ISSUE TITLE
DescendantNodes extension method throws NullReferenceException

### ISSUE THREAD

**Issue by forensicmike** [sebastienros/esprima-dotnet#230]
Hi, 

Currently on the latest nuget package version of 2.1.3.

I am getting a NullReferenceException with the following code which is meant to locate all VariableDeclaration nodes in a script.

```csharp
script.ChildNodes.SelectMany(z => z.DescendantNodesAndSelf().OfType<VariableDelcaration>()).ToList();
```

After some debugging, I traced the problem to this method contained within `Esprima.Ast.NodeExtensions`:

![image](https://user-images.githubusercontent.com/44839768/158248399-102f84e8-27c4-4bf8-8698-04b4cc43748e.png)

On the line `node.ChildNodes`, `node` is not null checked, and seems to be null quite a lot of the time.

I created my own extension method that checks for null and the exceptions went away.
E.g.
```csharp
private static IEnumerable<Node> DescendantNodes(List<Node> nodes)
        {
            while (nodes.Count > 0)
            {
                Node node = nodes[0];
                nodes.RemoveAt(0);
                yield return node;
                if (node is not null)
                {
                    nodes.InsertRange(0, node.ChildNodes);
                }
            }
        }
```

**Comment by sebastienros** [comment]
Can you share the JS script that generates a null value here?

**Comment by forensicmike** [comment]
Hi, I found a publicly available script I can share that seems to trigger it:
https://raw.githubusercontent.com/0xdea/frida-scripts/master/raptor_frida_ios_trace.js

**Comment by forensicmike** [comment]
I should note that with the null check in place, everything else seems to work great.
