### ISSUE TITLE
Work on Decorators

### ISSUE THREAD

**Issue by jogibear9988** [sebastienros/esprima-dotnet#255]
As Ddecorators are now also in Stage 3, and landed in the ES-Tree spec:

https://github.com/estree/estree/blob/master/stage3/decorators.md

Should I implement them in Esprima-next? Is it planed to add them here? Or does anyone already work on them? (So we again nearly share the same implemntation)

**Comment by lahma** [comment]
Everything that gets into test262 suite will also be a target here. I don't think anyone is currently working on them (no tests yet to target against), so probably a nice idea to start the work on next's side and then port back here.

**Comment by lahma** [comment]
Ah, I see that latest test262 suite update already started to bring the decorators stuff in! 

https://github.com/sebastienros/esprima-dotnet/pull/254/files#diff-1c5013fc21c03346aac755522c97bfd67943325a471ffe53f1a7de8c4b61081a
