### ISSUE TITLE
Program.ToString() does not return correct js content

### ISSUE THREAD

**Issue by ionuttamas** [sebastienros/esprima-dotnet#26]
Doing:

`var program = new JavaScriptParser().Parse(js);
Assert.AreEqual(js, program.ToString())`

does not work. Is there a way to get the js text value from the program?

**Comment by lahma** [comment]
Why don't you just keep a record of the js content you used to get the parsed version? Parsing produces AST which is quite hard to backtrack to original string format.

**Comment by sebastienros** [comment]
Duplicate of #8
