### ISSUE TITLE
Change fields to properties

### ISSUE THREAD

**Issue by lahma** [sebastienros/esprima-dotnet#264]
As it's been a nagging pain, we should try what perf consequences we get from doing so. Should have large JS file benchmark with no-op sealed `AstVisitor` running and see if there's anything of concern.

I'm creating some issues to track v3 ideas and progress.

/cc @adams85

**Comment by adams85** [comment]
This is also related to https://github.com/sebastienros/esprima-dotnet/issues/66

**Comment by adams85** [comment]
Can be closed (resolved by https://github.com/sebastienros/esprima-dotnet/pull/270)
