### ISSUE TITLE
Fix class-related parsing problems

### ISSUE THREAD

**Issue by lahma** [sebastienros/esprima-dotnet#265]
Assigning to myself as work started with https://github.com/sebastienros/esprima-dotnet/pull/248 , trying to get problems to zero.

**Comment by lahma** [comment]
And of course @jogibear9988 , see above, sorry I missed you - you three have been most active recently - and help is much appreciated! Refer to family and friends to get even more traction 😉

**Comment by jogibear9988** [comment]
I've never looked what problem still exist...
Only if someone mentioned some issues, I looked after them. :-)

I still have some pull request I need to look after:
https://github.com/node-projects/esprima-next/issues/24

and also I need to look at all pull requests after #222, wich I need to add also to esprima-next

**Comment by adams85** [comment]
> please keep refactoring to minimum when it comes to class related things

May I proceed with https://github.com/sebastienros/esprima-dotnet/issues/264 or would I rather wait until this is resolved?

**Comment by lahma** [comment]
@adams85 please go ahead!

**Comment by jogibear9988** [comment]
should we close this? i think most works at the moment

**Comment by lahma** [comment]
I think we should keep this open just a little bit longer. Probably when `allow-list.txt` does not have class-related relaxations this should be quite complete 🙂

**Comment by adams85** [comment]
I believe this is completed now, right?

**Comment by lahma** [comment]
Some validation still missing like hoisting scope names but this can be closed.
