### ISSUE TITLE
In some cases nodes are enumerated/visited multiple times

### ISSUE THREAD

**Issue by adams85** [sebastienros/esprima-dotnet#288]
While working on the enumeration of child nodes, I noticed that there are some cases where child node references are reused. Because of this these nodes are enumerated/visited multiple times.

The problematic node types are:
* `ExportSpecifier`: `Local` and `Exported` are the same node instance when export name is not specified. For example: `export { a }`
* `ImportSpecifier`: `Imported` and `Local` are the same node instance when local name is not specified. For example: `import { b } from 'x'`
* `Property`: `Key` and `Value` are the same node instance when it's a shorthand property of an object expression. For example: `({ c })`. Interestingly, in the case of an object pattern the parser doesn't reuse the node instance (`var { v } = { }`). So, we also have some inconsistency here.

I'm quite puzzled as to how to handle this. Should we do anything about this at all?

**Comment by lahma** [comment]
So is your suggestion maybe to have then nullable and nulll when they are missing from the AST?

**Comment by adams85** [comment]
I think the model is fine (AST explorer generates the same AST), so I wouldn't change that. It just feels off that the enumeration includes the same node instance multiple times.

What we could possibly do is to check for these cases and make sure these nodes are enumerated/visited only once.

However, there's the case of shorthand properties of object patterns. Consider `var { v } = { }` first. In this case the parser doesn't use the same `Identifier` instance for `Key` and `Value` but creates two separate instances *with the same content* (as opposed to the case of object expression shorthand properties, where only a single instance is created).

Take another example: `var { v = 0 } = { }`. Now `Value` is an `AssignmentExpression` whose `Left` property is the same identifier as `Key`. Also two different `Identifer` instances with the same content are created but in this case they don't even have the same parent node...

How to deal with this? The only correct way I can think of is to change the parser (to be precise, `ParsePropertyPattern`) to reuse the `Key` instance in the case of shorthand properties. Then change the enumeration/visitation to skip the `Key` node in such cases.

**Comment by lahma** [comment]
I don't have a strong opinion here. I always have my Jint glasses on so basically for Jint approach doesn't matter, Jint handles the content of AST without worrying of identity.

Would "back to javascript" be a good use case to prove if the current model is problematic? Like does double-visiting make things hard if not impossible. 

I don't se much harm in tweaking the `ParsePropertyPattern` logic.
