### ISSUE TITLE
Removing Json.NET dependency

### ISSUE THREAD

**Issue by sebastienros** [sebastienros/esprima-dotnet#3]
Currently necessary to run the tests. A solution is to create another project that is intended for serialization (Json and scripts) that would contain the rendering logic instead of decorating the AST with Json.NET attributes.

**Comment by R2D221** [comment]
You could check Json.NET's documentation. If I remember correctly, it's compatible with some attributes from the standard library.

**Comment by sebastienros** [comment]
@R2D221 they are not sufficient, for instance for enumerations.

Also, not for myself: Remove Token.Value as this is only necessary to render the json, and Regex needs to be moved to RegexValue and handled specifically in Json.

**Comment by atifaziz** [comment]
This seems fairly straightforward so no reason to have the dependency. Would you welcome a PR for this?

**Comment by atifaziz** [comment]
> It doesn't look straightforward to me ..

Interesting. The way I am looking at it, you just remove all the attribute decorations and implement the serialization of the AST as an implementation of `EsprimaVisitor`. It shouldn't be complicated.

Besides removing the dependency, it also has the advantage of affording more control. For example, `Node.Range` is an array…

https://github.com/sebastienros/esprima-dotnet/blob/1c5d809e1db4c2bfc23dfc259e23366984a6b81d/src/Esprima/Ast/Node.cs#L14

…when it doesn't need to be and seems like an inefficient in-memory representation. It seems (unless I am mistaken) to have been typed so for sake of serialization.

**Comment by sebastienros** [comment]
And next you write the Javascript serialization visitor?

**Comment by atifaziz** [comment]
> Good idea. 

Great, so we're on the same page now.

> And next you write the Javascript serialization visitor?

That's right.

So safe to say you would welcome a PR using this approach?

**Comment by atifaziz** [comment]
I am thinking of only removing the dependency from the core library and not the test or other projects in the repo.

**Comment by sebastienros** [comment]
That's good

**Comment by atifaziz** [comment]
@sebastienros This has been closed by ab2c954653218bc2f81462bdfdb507b6f05b75e7.
