### ISSUE TITLE
Eliminate JavaScript letter casing inconsistencies

### ISSUE THREAD

**Issue by adams85** [sebastienros/esprima-dotnet#303]
Unfortunately, the AST to JS feature was implemented with an inconsistent letter casing: "Javascript" was used in code and file names instead of "JavaScript". The confusion probably came from the parser class: it's named "JavaScriptParser" but it resides in a file named "JavascriptParser.cs".

Anyway, this inconsistency should be addressed before releasing v3. I think we'd better stick to the letter casing "JavaScript". (This one is used in .NET BCL too: e.g. `HttpUtility.JavaScriptStringEncode` or `JavaScriptEncoder`.)

So we have the following tasks:
* [x] Correct the letter casing in the code.
* [ ] Correct the letter casing in the file names. (This looks however somewhat problematic, especially in the case of *JavascriptParser.cs*, as it would probably cause merge conflicts and possibly mess up git blame. So if we want to do this, we'd better do it right before the production release, after everything else has been done for v3.)

**Comment by jogibear9988** [comment]
As I'm developing on Windows, FileName Casing does not matter, wich is often a problem. So normaly I rename the file to a complete new name, commit, and then rename it again to the new wished one

**Comment by jogibear9988** [comment]
close?

**Comment by adams85** [comment]
Nope, file names should be made consistent with the names of classes they contain if that doesn't mess up git blame (much).

> So normaly I rename the file to a complete new name, commit, and then rename it again to the new wished one

I've tested it and it looks like git is case-sensitive, thus, it allows us to do this in one pass. E.g. you can rename *JavascriptParser.cs* to *JavaScriptParser.cs*.

**Comment by adams85** [comment]
Nope, file names should be made consistent with the names of classes they contain if that doesn't mess up git blame (much).

> So normaly I rename the file to a complete new name, commit, and then rename it again to the new wished one

I've tested it and it looks like git is case-sensitive, thus, it allows us to do this in one pass. E.g. you can rename `JavascriptParser.cs` to `JavaScriptParser.cs`.

**Comment by jogibear9988** [comment]
yes, but i think then a checkout on windows could produce problems. (we had some)

**Comment by jogibear9988** [comment]
cause i think i windows you could not rename only caseing changes

**Comment by jogibear9988** [comment]
but i could be wrong

**Comment by lahma** [comment]
On Windows, you need to use git command line to do case-only change: https://stackoverflow.com/questions/1793735/change-case-of-a-file-on-windows#1793757

**Comment by adams85** [comment]
Thanks for the info!

**Comment by jogibear9988** [comment]
but it could lead to problems: https://stackoverflow.com/a/15640313

**Comment by adams85** [comment]
> Doing this can lead to changes that are impossible to merge.

Then it's clear that we need to do this after all pending PRs have got merged. As I wrote above: "So if we want to do this, we'd better do it right before the production release, after everything else has been done for v3."

**Comment by lahma** [comment]
No need to wait for my class-parsing. If it's single rename (single file?) commit I can just move file content under new file name.

**Comment by adams85** [comment]
It's not a single rename, there are a bunch of file names out of sync with the contained class name. But this is absolutely low priority (doesn't affect the release binaries), so we'd better just do it right before the release.
