### ISSUE TITLE
Big drop in possible maximum value of MaxAssignmentDepth

### ISSUE THREAD

**Issue by adams85** [sebastienros/esprima-dotnet#326]
After the latest perf. improvement release, test runs have started to fail with `StackOverflowException` in Debug builds on .NET 6. I looked into the issue and I've discovered something which, I'm afraid, may spoil our joy over the awesome results:

I've found that the maximum possible value of `ParserOptions.MaxAssignmentDepth` has drastically been decreased. On .NET 6 the following snippet starts to crash around `depth = 150` in Debug builds and around `depth = 250` in Release builds.

```csharp
const int depth = 200;
var input = $"if ({new string('(', depth)}true{new string(')', depth)}) {{ }}";
var parser = new JavaScriptParser(input, new ParserOptions { MaxAssignmentDepth = 1000 });
parser.ParseScript();
```

These numbers look pretty tight in the light of [this recent change](https://github.com/sebastienros/esprima-dotnet/pull/287):

> I also increased the max depth to 200, as the main config javascript file for AWS hits the 100 limit.

It's not hard to guess who's the main culprit: struct `Token`s greatly reduced heap allocations but significantly increased stack usage... According to my tests heap-allocated `Token`s allow max. depths around 600-700.

@lahma What's your thoughts on this? Should we revert to heap-allocated `Token`s? The current situation seems to be on the edge pretty much. I got these numbers on Windows, where 1MB is the stack size IIRC but there are other platforms which allows less stack space by default...

**Comment by lahma** [comment]
First of all, I think we should only worry about release build behavior, it's a whole different binary from a debug build. If we've had success with hard-coded value of 100 before I wouldn't be that concerned, but this is probably something to investigate a bit further.

If we'd find a way to transform some recursion to looping we would both increase the limit of possible handling and probably would get better perf - stack handling in recursion is quite costly.

**Comment by lahma** [comment]
I think I might have some ideas, I'll do some experiments hopefully this evening..

**Comment by CharlieEriksen** [comment]
Out of curiosity: What are the use-cases for parsing out tokens? I have never needed it so far.  So I always configure my parsers with them disabled :)

**Comment by adams85** [comment]
> If we've had success with hard-coded value of 100 before I wouldn't be that concerned

As I mentioned, [limit of 100 has already been hit in the wild and thus had to be increased](https://github.com/sebastienros/esprima-dotnet/pull/287#issue-1287481216). Plus the numbers I mentioned applies to Windows but, for example, [default stack size on macOS is 512KB for secondary threads](https://forums.swift.org/t/increase-size-of-stack/14493). Which, at a rough estimate, means a max. depth of 125 in Release builds which is pretty close.

The problem is concerning because SOE is a non-catchable exception and brings the process down even if it occurs in a background thread. (BTW, this also has implications for security in cases where parser is fed with user-provided input. The only guard we have in place against this is `MaxAssignmentDepth` currently.)

> If we'd find a way to transform some recursion to looping we would both increase the limit of possible handling and probably would get better perf - stack handling in recursion is quite costly.

Tail call recursion can be rewritten into loops for sure but at a quick glance there's not many candidates for that currently. Might be possible with some refactoring though.

Another thing to look for is redundant declaration of local variables (especially, larger structs). Not sure how good is JIT at optimizing this but may worth a try.

> Out of curiosity: What are the use-cases for parsing out tokens? I have never needed it so far. So I always configure my parsers with them disabled :)

For example, it's needed for syntax highlighting. However, we aren't talking about tokens returned for the consumer. `Scanner` also spits out tokens and parser needs these to do its thing. We've even split these two kinds of token representation into two types recently: `SyntaxToken` and `Token`. The latter was changes to a value type, which causes the unfortunate side-effect we're discussing here.
