### ISSUE TITLE
Issue with spread/rest operator

### ISSUE THREAD

**Issue by CharlieEriksen** [sebastienros/esprima-dotnet#336]
I've had run into some interesting issues the last day or two with what appears to be some issues with parsing the spread/rest operator.

Here's an example of a file that gives me issues:
[https://a.b.cdn.console.awsstatic.com/94ba18060d227fd28eba4cf63dc3a95189066a605c574d7af6eb6d3b2d3ac7ad/main.js](https://a.b.cdn.console.awsstatic.com/94ba18060d227fd28eba4cf63dc3a95189066a605c574d7af6eb6d3b2d3ac7ad/main.js). 

Here's the function that fails to parse:
```js
 function useI18N($) {
      const ie = useCurrentLocale(), [oe, se] = Object(le.useState)(ht);
      return Object(le.useEffect)(() => {
        se(ht), (async () => {
          const oe = await async function loadI18N($) {
            const ie = Et[$];
            return ie ? { i18n: ie, isFallback: !1 } : { i18n: ot, isFallback: !0 };
          }(function getStringsCompatibleLocale($) {
            return gt[$] || $;
          }($ || ie));
          se($ => ({
            ...$,
            ...oe,
            loading: !1
          }));
        })();
      }, [ie, $, se]), oe;
    }
```

It really doesn't seem to like the spread operators. From what I can tell, this syntax is not super recent (ES9/2018). So surely this should be parseable?

**Comment by adams85** [comment]
Absolutely and according to my tests [the latest beta](https://www.nuget.org/packages/Esprima/3.0.0-beta-6) parses both the function and the whole bundle without problems.

So I'm not sure what's going on here. Could you provide some additional details on your environment (lib version, runtime version, platform, OS, etc.)

**Comment by CharlieEriksen** [comment]
Damn, go figure. I should have tried to migrate to the latest beta. I went ahead and upgraded from `preview-99` to `beta-6`. And now it parses. 

Thanks! :D

**Comment by adams85** [comment]
As a matter of fact, on my side it works just fine with `preview-99` as well. Which is not surprising as that area of the library hasn't received significant changes for a while. So I'm pretty puzzled as to how come that version update solved your issue... 😕
