### ISSUE TITLE
Wrong handling of private Identifierers

### ISSUE THREAD

**Issue by jogibear9988** [sebastienros/esprima-dotnet#354]
Try this:

        class aa {
            #aa = true;
        }

We do not create an instance of PrivateIdentifier. We create a normal node with "#" in the value

**Comment by lahma** [comment]
This should now be covered too.

**Comment by adams85** [comment]
Unfortunately, not completely. Static private property and method declarations  like

```js
class X {
  static #privateField = 'super';
  static #getPrivateField() {
    return X.#privateField;
  }
}
```

are still parsed incorrectly as `Identifier`s. (Non-static declarations are OK.)

**Comment by jogibear9988** [comment]
fixed in my pull, missed one parameter
