### ISSUE TITLE
Version 3.0.0-beta-10 suffix problem

### ISSUE THREAD

**Issue by Taritsyn** [sebastienros/esprima-dotnet#374]
Hello!

Due to the fact that initially one number was used for numbering beta versions, now there are problems with the 10th beta. At the moment, NuGet package manager considers that the 10th beta is chronologically between the 1st and 2nd betas:

![esprima-versions](https://user-images.githubusercontent.com/251859/218778766-5b061c8d-a2be-47dd-8a26-b648a35351dd.png)

In addition to the problem with updating the Esprima .NET library itself, there is also a problem with updating the Jint library in .NET Framework projects (after update, the Jint library continues to use the Esprima .NET version 3.0.0-beta-9).

Ways to solve this problem:

 1. Change the version patch number: `3.0.1-beta-01`.
 1. Change the version suffix: `3.0.0-rc-01`.

**Comment by sebastienros** [comment]
Shift by 9000, using 3.0.1 would mean losing, 3.0.0. Not sure it's a big issue though.

beta-90001

**Comment by lahma** [comment]
With "final" public API review we probably would be quite close to just releasing 3.0 (or RC). Impossible to prepare for new language features anyway... 3.1 then.

/cc @adams85 @jogibear9988

**Comment by sebastienros** [comment]
There is also the preview suffix then

**Comment by lahma** [comment]
> There is also the preview suffix then

MyGet releases use that already, large running number. NuGet gets from tag.

**Comment by adams85** [comment]
I vote for `3.0.0-rc-01` as I'd like to include [this pending PR of mine](https://github.com/sebastienros/esprima-dotnet/pull/372) in 3.0.

> if anyone did not get it, import assertions proposal was rejected to stage 2

This is news to me. Then I'd also like this to be removed from the final 3.0. I can take this if you agree. Expectedly I'll have some free time at the weekend.

**Comment by jogibear9988** [comment]
> This is news to me. Then I'd also like this to be removed from the final 3.0. I can take this if you agree. Expectedly I'll have some free time at the weekend.

it's mentioned here: https://dev.to/hemanth/updates-from-the-94th-tc39-meeting-48mb

**Comment by jogibear9988** [comment]
but also stated in the slides here: https://docs.google.com/presentation/d/1HbWhyo4tSnpv4vMZqCa2YQvi_mKdpDi4JWWBtSUQqQY/edit#slide=id.g1f8a07b0c2b_0_124

they may keep the assert for backward compatibility.
it already shipped in chrome and safari tech preview

**Comment by adams85** [comment]
Slide 23 says "Please don't ship anything yet, if you haven't already done so!" It also looks like they haven't even decided on the syntax. Quote from the [proposal page](https://github.com/tc39/proposal-import-assertions):

> This proposal has been demoted from Stage 3 to Stage 2 in January 2023 due to https://github.com/whatwg/html/issues/7233. TC39 is working on a solution, which will require relaxing the "assert only" semantics and **potentially changing the syntax**. Import assertions have already been shipped in some implementations, consider the current instability when using them.

Regardless of what chrome and safari devs do, I still don't like the idea of including this feature at the moment.

**Comment by lahma** [comment]
Esprima 3.0.0-rc-01 has been published to NuGet and Jint has been updated to consume the new RC package, closing this as complete. Thanks for the problem report and discussion around it!
