### ISSUE TITLE
Import Assertions (aka Import Atributes) are back at stage 3 so we should add them again

### ISSUE THREAD

**Issue by jogibear9988** [sebastienros/esprima-dotnet#380]
see: https://github.com/tc39/proposal-import-attributes

**Comment by jogibear9988** [comment]
we also need to rename the property "assertions" to "attributes", see : https://github.com/estree/estree/blob/master/experimental/import-attributes.md

**Comment by adams85** [comment]
[PR](https://github.com/sebastienros/esprima-dotnet/issues/380) is ready but let's not merge it yet. I wrote about the why in the PR description.
