### ISSUE TITLE
Inconsistencies with ESTree

### ISSUE THREAD

**Issue by adams85** [sebastienros/esprima-dotnet#382]
We have a statement in the readme saying:

> Sensible [syntax tree format](https://github.com/estree/estree/blob/master/es5.md) as standardized by [ESTree project](https://github.com/estree/estree)

The first part is true but I'm afraid we can't claim that we strictly adhere to the ESTree standard at the moment as there are some differences between ESTree and our model. Personally, I'm ok with most of these differences as they are more or less forced by C#'s type system or in some cases the design choices of ESTree just look suboptimal from a practical standpoint. E.g in the standard model
* `LogicalExpression` doesn't extend `BinaryExpression`,
* `PrivateIdentifier` extends `Node` whereas `Identifer` extends `Expression`,
* `Super` extends `Node` whereas `ThisExpression` extends `Expression`,
* etc (I can list a few more if you're interested).

There may be theoretical reasons for these design choices but I'm quite happy with our AST model because it has proven to work pretty well in practice. However, I suggest changing the aforementioned statement to something like "Sensible [syntax tree format](https://github.com/estree/estree/blob/master/es5.md) **which follows the standard** established by the [ESTree project](https://github.com/estree/estree)".

I found only one issue (a naming inconsistency) which still contradicts this claim somewhat: [the standard name of dynamic import nodes is `ImportExpression`](https://github.com/estree/estree/blob/70f89cddd0bb3d9842847314d34c32f315b9336d/es2020.md#importexpression) instead of `Import`. This is the other change I'd like to make. Of course, this would be a BC and we're past the beta phase, so
* are you ok with this change at this point or 
* would you postpone it until the next major version or 
* wouldn't bother about it at all?

**Comment by lahma** [comment]
> "Sensible [syntax tree format](https://github.com/estree/estree/blob/master/es5.md?rgh-link-date=2023-04-09T14%3A57%3A24Z) which follows the standard established by the [ESTree project](https://github.com/estree/estree)".

Sounds good.

>  This is the other change I'd like to make. Of course, this would be a BC and we're past the beta phase, so

I'm team "ok with this change at this point". The idea with next major release is "to break as much as we can to get things cleaned up". I don't expect it's a break the world situation if binary compatibility is broken between RC and release. Not many bother ticking the box in NuGet explorer to get preview releases...
