### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by adams85** [sebastienros/esprima-dotnet#400]
Readme is kinda outdated, update it before final 3.0.

**Comment by adams85** [comment]
Would be nice to see how v3.0 compares to v2 and other parsers and update the [benchmark section](https://github.com/sebastienros/esprima-dotnet#benchmarks) in the readme too. @lahma Would you like to play with this maybe?

**Comment by lahma** [comment]
I believe that the results were extracted using [benchmarks on esprima.org site](https://esprima.org/test/benchmarks.html). I just now don't get results for all of them and for the ones that I get, they are way worse than what readme describes.

**Comment by adams85** [comment]
Hmm, that's interesting, on my machine those benchmarks run fine (both in Chrome and FF)... But don't bother with it then, I'll update the benchmark section, too.

**Comment by lahma** [comment]
Tried even on second machine and I still get only partial results from fast benchmarks, I don't have an idea what's going on...

![image](https://github.com/sebastienros/esprima-dotnet/assets/171892/1be7b9d3-6ebc-4ec1-b273-f07396aa5420)

**Comment by adams85** [comment]
Looks like fast benchmarks have some issues. Full benchmarks return complete results.
