### ISSUE TITLE
InvalidCastException during ObjectPropertyKey parsing

### ISSUE THREAD

**Issue by KvanTTT** [sebastienros/esprima-dotnet#41]
### Input

From http://es6-features.org/#ComputedPropertyNames:

```javascript
let obj = { [ "baz" + quux() ]: 42 }
```

### Expected

Successful parsing.

### Actual

```
System.InvalidCastException: 'Unable to cast object of type 'Esprima.Ast.BinaryExpression' to type 'Esprima.Ast.PropertyKey'.'
```

**Comment by sebastienros** [comment]
I know how to fix it now, there is a PR with same issue already but now I understand it better with this example.
