### ISSUE TITLE
Unable to modify Arguments Literal value from AST using AstRewriter

### ISSUE THREAD

**Issue by PraveenNemagoudar** [sebastienros/esprima-dotnet#438]
**Version used** : version 3.0.4

**Describe the bug**

I am trying to modify Arguments Literal Value of a function call. I am unable to edit as it is read-only and I tried creating new argument and add literal but creating new  NodeList<Expression>() with one or two arguments constructor giving error and it does not have Add method also to add Literal.

Here is the source code:

    public class ArgumentRewriter : AstRewriter
    {
        public ArgumentRewriter(){}
		
        protected override object VisitCallExpression(CallExpression callExpression)
        {
            if (callExpression.Callee is Identifier calleeId && calleeId.Name.StartsWith("MyFunction"))
            {
                var functionName = calleeId.Name;
                var argumentLiteral = callExpression.Arguments.FirstOrDefault() as Literal;

                if (argumentLiteral != null && _argumentHandlers.TryGetValue(functionName, out var handler))
                {
                    var modifiedLiteral = handler(argumentLiteral);
                    var newStringLiteral = new Literal(modifiedLiteral);

                     // Try 1 : Modify directly the literal value of arguments
                    argumentLiteral.Value = "newName";
                **// error CS0200: Property or indexer 'Literal.Value' cannot be assigned to -- it is read only**

                    //Try 2 : Create new Argument and add literal value and update the function
                    var newArguments1 = new NodeList<Expression>();		
                    newArguments1.Add(newStringLiteral);
		    **// error CS1061: 'NodeList<Expression>' does not contain a definition for 'Add'**

                    //Try 3 : Create new Argument object with new literal
                    var newArguments = new NodeList<Expression>(newStringLiteral);
		    **// error CS1729: 'NodeList<Expression>' does not contain a constructor that takes 1 arguments**

                    //Try 4 : Create new Argument object with new literal
                    Expression[] expressionArray = new Expression[] { newStringLiteral };
                    NodeList<Expression> nodeList = new NodeList<Expression>(expressionArray, 1);
		    **// error CS1729: 'NodeList<Expression>' does not contain a constructor that takes 2 arguments**

                    //Try 5 : Create new Argument object with new literal
                    List<Expression> expressionList = new List<Expression>();
                    expressionList.Add(newStringLiteral);
                    Expression[] expressionArray1 = expressionList.ToArray();
                    NodeList<Expression> nodeList1 = new NodeList<Expression>(expressionArray1, expressionArray1.Count);
		    **// error CS1729: 'NodeList<Expression>' does not contain a constructor that takes 2 arguments**

                    return callExpression.UpdateWith(callExpression.Callee, newArguments);
                }
            }

            return base.VisitCallExpression(callExpression);
        }
    }
	
//From Main()
var rewriter = new ArgumentRewriter();
rewriter.Visit(ast);

//HELP
Please help how to modify Arguments Literal value of function using AST Rewriter.

**Comment by adams85** [comment]
Hey @PraveenNemagoudar,

I think you're looking for [the `NodeList.Create` method](https://github.com/sebastienros/esprima-dotnet/blob/main/src/Esprima/Ast/NodeList.cs#L194). This is the API publicly available for consumers to create `NodeList`s.

**Comment by PraveenNemagoudar** [comment]
Thank you.
