### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by JarLob** [sebastienros/esprima-dotnet#46]
This sample produces the error:
```
a = async function() {
}

```
http://esprima.org/demo/validate.html handles it.

**Comment by sebastienros** [comment]
async functions are not supported yet. Esprima-dotnet only handles es6 syntax for now.

**Comment by samuela** [comment]
Has there been any update on this? I'm still seeing this error.

**Comment by samuela** [comment]
@lahma Yes, I ended up finding out that a dependency had a dependency on esprima but pinned to an older version. That seems to have been the root cause!
