### ISSUE TITLE
Add test for Octal literals in strict mode

### ISSUE THREAD

**Issue by sebastienros** [sebastienros/esprima-dotnet#6]
`var s = '\37'` should return `Messages.StrictOctalLiteral`

**Comment by sebastienros** [comment]
This is correctly tested in esprima, the issue must be that the error checks are not correct.

**Comment by lahma** [comment]
Checked and works as expected. Configuration needs to be `Tolerant=false` and `strict=true` (or script to have `'use strict';`).
