### ISSUE TITLE
AST API has inconsistencies

### ISSUE THREAD

**Issue by atifaziz** [sebastienros/esprima-dotnet#66]
The AST API currently contains a few inconsistencies, fixing which would go a long way to polish things up for 1.0.

The majority of the AST appears to be read-only except in a few select cases, most of which seem to be unused (or are/were supporting Jint?). The biggest read-write structure seems to be `List<>` but `List<>` is not designed to be exposed in the public API surface of a class library anyway. I suggest rendering the entire public AST data structures read-only for sake of consistency, if not for other benefits that may stem from that like naturally thread-safe structures due to their immutability.

There is also mixed use of fields and properties. It would seem best to consistently expose properties.

The table below shows all node classes of the AST with fields and properties. It shows the mixed use of the two. I've also highlighted read-write properties/fields with an asterisk (*), which would need review to make the AST immutable.

| Type | Fields | Properties |
|------|--------|------------|
| `ArrayExpression` | `Elements` |  |
| `ArrayPattern` | `Elements` |  |
| `ArrowFunctionExpression` | `Id`, `Params`, `Body`, `Generator`, `Expression`, `HoistingScope`\* |  |
| `ArrowParameterPlaceHolder` | `Params` |  |
| `AssignmentExpression` | `Operator`, `Left`, `Right` |  |
| `AssignmentPattern` | `Left`, `Right`\* |  |
| `BinaryExpression` | `Operator`, `Left`, `Right` |  |
| `BlockStatement` | `Body` |  |
| `BreakStatement` | `Label` |  |
| `CallExpression` | `Callee`, `Arguments`, `Cached`\*, `CanBeCached`\*, `CachedArguments`\* |  |
| `CatchClause` | `Param`, `Body` |  |
| `ClassBody` | `Body` |  |
| `ClassDeclaration` | `Id`, `SuperClass`, `Body` |  |
| `ClassExpression` | `Id`, `SuperClass`, `Body` |  |
| `ConditionalExpression` | `Test`, `Consequent`, `Alternate` |  |
| `ContinueStatement` | `Label` |  |
| `Directive` | `Directiv` |  |
| `DoWhileStatement` | `Body`, `Test` |  |
| `ExportAllDeclaration` | `Source` |  |
| `ExportDefaultDeclaration` | `Declaration` |  |
| `ExportNamedDeclaration` | `Declaration`, `Specifiers`, `Source` |  |
| `ExportSpecifier` | `Exported`, `Local` |  |
| `ExportStatement` | `Expression` |  |
| `ExpressionStatement` | `Expression` |  |
| `ForInStatement` | `Left`, `Right`, `Body`, `Each` |  |
| `ForOfStatement` | `Left`, `Right`, `Body` |  |
| `ForStatement` | `Init`, `Test`, `Update`, `Body` |  |
| `FunctionDeclaration` |  | `Id`, `Params`, `Body`, `Generator`, `Expression`, `HoistingScope`, `Strict` |
| `FunctionExpression` |  | `Id`, `Params`, `Body`, `Generator`, `Expression`, `HoistingScope`, `Strict` |
| `Identifier` | `Name` |  |
| `IfStatement` | `Test`, `Consequent`, `Alternate` |  |
| `ImportDeclaration` | `Specifiers`, `Source` |  |
| `ImportDefaultSpecifier` | `Local` |  |
| `ImportNamespaceSpecifier` | `Local` |  |
| `ImportSpecifier` | `Local`, `Imported` |  |
| `LabeledStatement` | `Label`, `Body` |  |
| `Literal` | `NumericValue`, `Regex`, `Value`, `Raw`, `TokenType`, `CachedValue`\* | `StringValue`, `BooleanValue`, `RegexValue` |
| `MetaProperty` | `Meta`, `Property` |  |
| `MethodDefinition` | `Static` |  |
| `NewExpression` | `Callee`, `Arguments` |  |
| `Node` |  | `Type`\*, `Range`\*, `Location`\* |
| `ObjectExpression` | `Properties` |  |
| `ObjectPattern` | `Properties` |  |
| `Program` | `Body`, `SourceType` | `HoistingScope`, `Strict` |
| `Property` | `Method`, `Shorthand` |  |
| `RestElement` | `Argument` |  |
| `ReturnStatement` | `Argument` |  |
| `SequenceExpression` |  | `Expressions`\* |
| `SpreadElement` | `Argument` |  |
| `Statement` |  | `LabelSet`\* |
| `SwitchCase` | `Test`, `Consequent` |  |
| `SwitchStatement` | `Discriminant`, `Cases` |  |
| `TaggedTemplateExpression` | `Tag`, `Quasi` |  |
| `TemplateElement` | `Value`, `Tail` |  |
| `TemplateLiteral` | `Quasis`, `Expressions` |  |
| `ThrowStatement` | `Argument` |  |
| `TryStatement` | `Block`, `Handler`, `Finalizer` |  |
| `UnaryExpression` | `Operator`, `Argument` | `Prefix`\* |
| `VariableDeclaration` | `Declarations`, `Kind` |  |
| `VariableDeclarator` | `Id`, `Init` |  |
| `WhileStatement` | `Test`, `Body` |  |
| `WithStatement` | `Object`, `Body` |  |
| `YieldExpression` | `Argument`, `Delegate` |  |

**Comment by atifaziz** [comment]
If there are no objections to the raised issues, I can try (time permitting) to tackle this and submit a PR.

**Comment by sebastienros** [comment]
@lahma will probably care about perf impact.

**Comment by lahma** [comment]
From Jint's viewpoint API with concrete types and fields instead of properties is optimal. It fights against API best practices but gives the best performance.

No JIT work for properties (might or might not get inlined) and fast `for` loops against concrete List without interface dispatch and enumerator allocations.

I'd like to see this considered, maybe in form of checking current BDN benchmarks for effects on changes. Of course Jint benchmarks give the best picture as it needs to go through AST as fast as possible.

**Comment by atifaziz** [comment]
@lahma We can keep fields if property access is a performance concern but properties have the benefit that we can keep the structure read-write internally (with internal setters) to help with the AST construction phase. Again, if you look at the table, there are very few cases and some members are already properties so I don't expect there to be a huge impact.

> No JIT work for properties (might or might not get inlined)

Practically all properties will be dumb and non-virtual accesses so I can't imagine why JIT would shy from inlining those.

> and fast `for` loops against concrete List without interface dispatch and enumerator allocations.

This won't happen if you introduce a `List<>` that's native to the AST namespace. In fact, you can save on allocations by even making it a `struct` since it's just a wrapper around an array. You'll keep all the same benefits of BCL's `List<>` while maintaining a clean and encapsulated API.

I don't know much about how Jint is implemented but my guess would be that immutable structures could pave the way to more _global_ optimizations eventually (e.g. sharing nodes and their optimizations across AST roots and scripts). Anyway, I might be getting ahead of myself and just speculating but my point is that there more than one way to skin the performance cat.

**Comment by lahma** [comment]
Release profiling has showed that JIT can skip dummy getters too, probably related to how much it allows itself to take time. So no need for JIT of course means not only faster startup but also possibly more resources available for JITting other stuff. But of course probably not the biggest thing like you said. INode being an interface brings some baggage too.

Custom struct list is a interesting idea indeed. So internal mutators and public gets I believe, sounds nice. Jint has its own internal Dictionary already based on corefxlab's DictionarySlim, haven't played with the idea of making it struct though... A thing for my todo list!

**Comment by adams85** [comment]
I think resolution of this issue has finally been completed with the recent changes.

**Comment by lahma** [comment]
Closing as done, we can open more specific issues if there's still work to be done. Thanks to all involved!
