### ISSUE TITLE
TitleCase property names in serialized ast

### ISSUE THREAD

**Issue by concubicycle** [sebastienros/esprima-dotnet#7]
`JsonConvert.SerializeObject(tokens, Formatting.Indented)` for an Exprima.Ast.Program results in JSON that has capitalized property names, (like `"Type": " "VariableDeclaration"`). In my case, this was a problem, because I was re-writing the source with esgodegen, which expects camelcase property names, and got tripped up. So, I used: 

`
var astJson =JsonConvert.SerializeObject(program,
                        new JsonSerializerSettings
                        {
                            ContractResolver = new CamelCasePropertyNamesContractResolver()
                        });
`

I couldn't quickly find the ESTree spec, so I'm not sure if it specified that property names should be camelcase. But I assume that they are largely expected to be, since that's the usual json convention. 

The Program, and various nodes, should probably get a [DataContract] with [DataMemeber] attributes, which specify camelcase property names.

**Comment by sebastienros** [comment]
Using `CamelCasePropertyNamesContractResolver` is the correct way to do it.
