### ISSUE TITLE
To Javascript

### ISSUE THREAD

**Issue by ghost** [sebastienros/esprima-dotnet#8]
Would it be possible to add a function that serialize it to javascript instead of JSON?

**Comment by sebastienros** [comment]
We just merged a PR that provides a visitor base class. Now we need someone to work on an implementation that serializes the tree back to JavaScript.
Would be interesting to have a mode that tries to match the initial format, and optional mode for formatting, like customizing indentation, or minifying.

**Comment by sebastienros** [comment]
Also, there is this JS library that does it already, https://github.com/estools/escodegen, maybe by using https://github.com/sebastienros/jint this would help. The JSON format rendered by esprima-dotnet is compatible on purpose.

**Comment by jogibear9988** [comment]
https://github.com/sebastienros/esprima-dotnet/pull/154

**Comment by jogibear9988** [comment]
now #291

**Comment by adams85** [comment]
Now it's implemented (apart from JSX) and available in [3.0.0-beta-3](https://www.nuget.org/packages/Esprima/3.0.0-beta-3).
